include: package:very_good_analysis/analysis_options.2.3.0.yaml

analyzer:
  errors:
    # ignore this in pubspec.yaml
    asset_does_not_exist: ignore
    unused_element: ignore
    avoid_dynamic_calls: ignore
    lines_longer_than_80_chars: ignore
  exclude:
    [
      build/**,
      lib/**.config.dart,
      lib/**.g.dart,
      template/**/*,
      lib/app/widgets/atoms/icons/icons.dart,
      lib/**.widgetbook.dart,
    ]

linter:
  rules:
    public_member_api_docs: false
    avoid_returning_this: false
